# Copyright (c) 2026 Alibaba Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""GRPO policy wrapper around CosyVoice3's flow model (CausalMaskedDiffWithDiT).

Differences from stock inference (cosyvoice/flow/flow_matching.py):
  * fresh N(0, I) initial noise per group sample instead of the fixed
    ``rand_noise`` buffer (the MDP initial distribution rho_0 is N(0, I));
  * classifier-free guidance is OFF during rollout (paper Sec 4.4.4: omitting
    CFG widens exploration and speeds up reward growth; standard inference
    keeps its usual CFG);
  * a contiguous window of ``window_size`` Euler steps starting at a random
    index in [window_start_min, window_start_max] is executed as SDE steps and
    recorded for RL updates; all remaining steps stay deterministic ODE.
"""

import math
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn.functional as F

from .sde_solver import (
    Transition,
    gaussian_logprob,
    make_t_span,
    ode_step,
    sample_window_start,
    sde_mean,
    sde_sigma,
)


class FlowGRPOPolicy:
    """Stateless helper; the trainable parameters live in ``flow`` (LoRA on the DiT)."""

    def __init__(self,
                 flow: torch.nn.Module,
                 n_timesteps: int = 10,
                 noise_level: float = 0.5,
                 window_size: int = 2,
                 window_start_min: int = 1,
                 window_start_max: int = 3,
                 logprob_reduction: str = 'mean'):
        self.flow = flow
        self.n_timesteps = n_timesteps
        self.noise_level = noise_level
        self.window_size = window_size
        self.window_start_min = window_start_min
        self.window_start_max = window_start_max
        self.logprob_reduction = logprob_reduction
        assert window_start_max + window_size <= n_timesteps, 'stochastic window exceeds trajectory'
        self.t_scheduler = flow.decoder.t_scheduler

    @property
    def device(self):
        return next(self.flow.parameters()).device

    @torch.no_grad()
    def prepare_conditions(self,
                           token: torch.Tensor,
                           prompt_token: torch.Tensor,
                           prompt_feat: torch.Tensor,
                           embedding: torch.Tensor) -> Dict[str, torch.Tensor]:
        """Builds the FM conditioning exactly like CausalMaskedDiffWithDiT.inference
        (offline mode, finalize=True), keeping batch size 1.

        Args:
            token: (1, L) speech tokens generated by the frozen LLM.
            prompt_token: (1, Lp) prompt speech tokens.
            prompt_feat: (1, T1, 80) prompt mel.
            embedding: (1, 192) campplus speaker embedding.
        Returns dict with mu/spks/cond/mask shaped for the DiT estimator plus
        ``prompt_mel_len`` marking where generated frames start.
        """
        flow = self.flow
        embedding = F.normalize(embedding, dim=1)
        spks = flow.spk_embed_affine_layer(embedding)

        token = torch.concat([prompt_token, token], dim=1)
        token_emb = flow.input_embedding(torch.clamp(token, min=0))
        h = flow.pre_lookahead_layer(token_emb)
        h = h.repeat_interleave(flow.token_mel_ratio, dim=1)

        mel_len1 = prompt_feat.shape[1]
        mel_len2 = h.shape[1] - mel_len1
        assert mel_len2 > 0, 'no frames to generate: token sequence shorter than prompt mel'

        conds = torch.zeros([1, h.shape[1], flow.output_size], device=h.device, dtype=h.dtype)
        conds[:, :mel_len1] = prompt_feat
        conds = conds.transpose(1, 2)

        mask = torch.ones([1, 1, h.shape[1]], device=h.device, dtype=h.dtype)
        return {
            'mu': h.transpose(1, 2).contiguous(),
            'spks': spks,
            'cond': conds,
            'mask': mask,
            'prompt_mel_len': torch.tensor(mel_len1),
        }

    def _expand_group(self, conditions: Dict[str, torch.Tensor], group_size: int) -> Dict[str, torch.Tensor]:
        out = {}
        for k, v in conditions.items():
            if k == 'prompt_mel_len':
                out[k] = v
            else:
                out[k] = v.repeat(group_size, *([1] * (v.dim() - 1)))
        return out

    def _velocity(self, x: torch.Tensor, cond: Dict[str, torch.Tensor], t: float) -> torch.Tensor:
        """Single-branch estimator call: no CFG during RL rollout/update."""
        t_vec = torch.full((x.shape[0],), t, device=x.device, dtype=x.dtype)
        return self.flow.decoder.estimator(x, cond['mask'], cond['mu'], t_vec, cond['spks'], cond['cond'],
                                           streaming=False)

    @torch.no_grad()
    def rollout(self,
                conditions: Dict[str, torch.Tensor],
                group_size: int,
                generator: Optional[torch.Generator] = None,
                window_start: Optional[int] = None) -> Tuple[torch.Tensor, List[Transition], int]:
        """Samples a group of G mel spectrograms sharing the same conditions.

        Returns (mel (G, 80, T) with the prompt region still attached,
        window transitions, window start index).
        """
        cond = self._expand_group(conditions, group_size)
        mu = cond['mu']
        if window_start is None:
            window_start = sample_window_start(self.window_start_min, self.window_start_max, generator)
        window = range(window_start, window_start + self.window_size)

        t_span = make_t_span(self.n_timesteps, self.t_scheduler, mu.device, mu.dtype)
        x = torch.randn(mu.shape, device=mu.device, dtype=mu.dtype, generator=generator)
        transitions: List[Transition] = []
        for step in range(self.n_timesteps):
            t = float(t_span[step])
            dt = float(t_span[step + 1] - t_span[step])
            v = self._velocity(x, cond, t)
            sigma = sde_sigma(t, self.noise_level)
            # sigma == 0 (noise_level 0) means no stochastic action at this step:
            # the transition is deterministic and has no likelihood to optimize
            if step in window and sigma > 0.0:
                mean = sde_mean(x, v, t, dt, sigma)
                std = sigma * math.sqrt(dt)
                noise = torch.randn(x.shape, device=x.device, dtype=x.dtype, generator=generator)
                x_next = mean + std * noise
                logp = gaussian_logprob(x_next, mean, std, cond['mask'], self.logprob_reduction)
                transitions.append(Transition(step=step, t=t, dt=dt, sigma=sigma,
                                              x_t=x.clone(), x_next=x_next.clone(), logprob_old=logp))
            else:
                x_next = ode_step(x, v, dt)
            x = x_next
        return x.float(), transitions, window_start

    def transition_logprob(self,
                           conditions: Dict[str, torch.Tensor],
                           transition: Transition,
                           group_size: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """Re-evaluates a stored transition under the *current* parameters (grad flows).

        Returns (logprob (G,), transition mean (G, 80, T)); the mean is reused
        for the closed-form Gaussian KL against the reference policy.
        """
        cond = self._expand_group(conditions, group_size)
        v = self._velocity(transition.x_t, cond, transition.t)
        mean = sde_mean(transition.x_t, v, transition.t, transition.dt, transition.sigma)
        logp = gaussian_logprob(transition.x_next, mean, transition.std, cond['mask'], self.logprob_reduction)
        return logp, mean
